import type { CardEffectModule } from '../types';

/**
 * The bolt's halo, shared by the css default and the far plane's hazier variant — one source, so the
 * two cannot drift apart. Stacked and opaque on purpose; see the note above the `.p` rule.
 */
const BOLT_GLOW =
  'drop-shadow(0 0 1px #ffffff) drop-shadow(0 0 3px #c4b5fd) drop-shadow(0 0 6px #a78bfa) drop-shadow(0 0 6px #7c3aed)';

/**
 * A bolt strikes the bottom edge and blows a flare out of the ground. The rare-event rhythm the nick
 * could not carry: ~95% of the cycle there is nothing at all, then a ~0.3s double-flicker. A card is
 * a big enough canvas for that to read as an event rather than as absence.
 *
 * Shape: the module can only emit styles, never markup — so the bolt is ONE element with a
 * `clip-path` polygon generated per particle. The outline runs down the left side through two bends,
 * hits the tip, and comes back up the right side, thinning as it goes; every viewer's bolt is a
 * different shape. Deliberately angular (anime), not fractal: a couple of bends read at 40px, a
 * branching tree does not.
 *
 * Two tricks worth keeping:
 * - The tip is FIXED at 50% of the element and the element is centred on its spawn column
 *   (`translate: -50%`). That is what lets the ground flare sit at plain `left: <spawn>` with no
 *   maths — compare card-stardust, which has to reproduce its own drift in the glow's `left`.
 * - `aspect-ratio` ties the bolt's width to the card's height, so the zigzag keeps its proportions
 *   in a 192px card and a 40px row alike. Doing that with container units would reintroduce the
 *   resize bug the falling effects just escaped.
 *
 * Nothing moves here, so none of the px/s smoothness rules apply: a bolt appears, it does not fall.
 *
 * DEPTH: three planes like everything else, but the only effect that shares none of ../depth's
 * machinery, because here the planes are not one thing at three distances — they are three different
 * phenomena. Every other effect can push a petal back by shrinking, slowing and softening it. A bolt
 * has no speed to scale (it appears, it does not travel), and it is nothing BUT silhouette, so blur
 * does not move it away, it only breaks it. The way out is to stop asking what a bolt looks like far
 * away and ask what you actually SEE at that distance:
 *
 * - FAR is the same bolt, generated by the same code, but small: a short channel high in the frame,
 *   dissolving into haze instead of reaching ground, its light scattered into a wide dim halo.
 * - MID is the bolt at full size, exactly as it always was — the subject, and the only one that
 *   lands a flare.
 * - NEAR is the strike hitting the card: the channel is wider than the frame, so there is no shape
 *   left to see, only the light. Violet floods everything, once, and is gone.
 *
 * The far plane was a soft radial "sheet flash" first, and it was the cheapest thing in the catalog:
 * an ellipse wider than its own card, so overflow sliced a straight edge through it, fading to
 * `transparent` — i.e. transparent BLACK — so what should have been a falloff was a grey ring. Both
 * were fixable, but the lesson was bigger than the bugs: this module owns a good bolt generator, and
 * a hand-drawn gradient next to it will always look like a sticker. Far is a REAL bolt, just small.
 *
 * `counts` stays a RATE rather than a density (bolts / dur), so the two new planes are extra slots
 * rather than bolts taken away — the storm's rhythm is the bolt rhythm and it is unchanged.
 */
export const cardLightning: CardEffectModule = {
  id: 'card-lightning',
  type: 'card_effect',
  costDust: 4000,
  className: 'card-fx-lightning',
  // Slots 0 and 1 are the far bolt and the flood; the REST are near bolts, and their rate is what the
  // storm's rhythm is made of — so these are the old 3/4/2 with the two new planes added on top,
  // never carved out. Bolt rate ≈ bolts / dur: still ~1.5s between strikes on a card, ~1.1s on an
  // alert, ~2.3s in a pill (a pill needs 4 for that, since two of its slots are not bolts).
  counts: { web: 5, overlayCard: 5, overlayChat: 4 },
  // Every strike is a NEW bolt, not the same silhouette blinking in a new column — and every flood
  // comes in from a new corner. Uniquely safe here: all three are pure geometry that no keyframe
  // animates (--bolt is a clip-path, --ar an aspect-ratio, --hx a gradient's origin), and a strike
  // is reborn at opacity 0. Elsewhere this list stays empty, because elsewhere it would mean
  // re-rolling size while --dur stays put — see CardEffectModule.
  respawnKeys: ['--bolt', '--ar', '--hx'],
  labels: { name: 'shop.cardLightning', desc: 'shop.cardLightningDesc' },
  particle: (rnd, compact, index) => {
    // A quota, like ../depth's, but this effect's own: the shared 1-in-7 rule assumes a swarm, and a
    // storm of five has no room for it. Slot 0 is always the far bolt, slot 1 the near flood, and
    // everything after is the bolt — so the counts above keep exactly the bolt rate they always had
    // and the two new planes are additions, not a tax (the same rule depthCount follows).
    const kind = index === 0 ? 'distant' : index === 1 ? 'flood' : 'bolt';
    // Negative delay = start mid-cycle, so nothing on the page strikes in unison on first paint.
    const timing = (d: number) => ({
      '--dur': `${d.toFixed(2)}s`,
      '--delay': `${(-rnd(0, d)).toFixed(2)}s`,
    });

    // The near plane is the only one with no channel to draw, so it is the only early exit.
    if (kind === 'flood') {
      return {
        // It owns the whole card, so it starts at the left edge with no centring offset.
        left: '0%',
        '--tx': '0%',
        '--pw': '100%',
        '--ph': '100%',
        // Where the strike went in; re-rolled per strike so the light does not always come from the
        // same corner (see respawnKeys).
        '--hx': `${rnd(15, 85).toFixed(0)}%`,
        // Every stop is the SAME violet at falling alpha, never `transparent`. `transparent` is
        // transparent BLACK, so a fade to it travels through grey and lays a dirty ring over the
        // card instead of dying cleanly. That mistake is what made the first far plane look cheap.
        '--fill': `radial-gradient(115% 85% at var(--hx, 50%) 100%, rgba(237, 233, 254, 0.95), rgba(167, 139, 250, 0.6) 38%, rgba(124, 58, 237, 0.28) 70%, rgba(124, 58, 237, 0) 92%)`,
        '--fx': 'none',
        '--bolt': 'none',
        '--flare': '0',
        '--op': rnd(0.5, 0.62).toFixed(2),
        animationName: 'cardfx-lightning-flood',
        // A near strike is rare, and its cycle IS that rarity. Raising the rate means shortening
        // this — and then widening the keyframe window by the same factor, because the window is a
        // % of the cycle and would otherwise quietly clip the flash shorter as it got more frequent.
        ...timing(rnd(9.5, 15)),
      };
    }

    // 'distant' is a real bolt, generated by the same code as the near one — that is the whole point
    // of it. Distance is angular: it is SHORT (it hangs from the cloud and its channel is lost to
    // haze long before any ground), thin, dim, and its light arrives scattered into a wide halo.
    const far = kind === 'distant';
    const dur = far ? rnd(4.5, 7) : rnd(3.5, 5.5);
    // Randomising the SEGMENT COUNT is what makes every bolt a different bolt rather than one
    // silhouette shifted around — and more bends read as more electric. Both surfaces want plenty:
    // nobody counts the bends, they read the vibe at a glance, and density IS the vibe. `compact`
    // only shifts the range down a little and unlocks the wider swing below — the SHAPE is
    // generated, so no amount of `.compact` CSS could adjust it downstream.
    const segments = compact ? Math.floor(rnd(4, 6.99)) : Math.floor(rnd(5, 8.99));
    // On a card the swing shrinks as bends multiply: without that the segments get shorter
    // vertically while still wandering just as far sideways, and the bolt becomes a zigzag ribbon.
    // A pill gets a FIXED generous swing instead — compensated at that scale the zigzag would be
    // narrower than the 2px line drawing it, i.e. a straight stick. Many bends in a short box are
    // unavoidably more diagonal; at pill size that density is exactly what reads as electric.
    const swing = () => (compact ? rnd(20, 36) : rnd(16, 40) * (3 / segments));
    // Thickness in PIXELS, tapering to a point at the tip. Not a % of the element: the element's
    // width scales with the card, so a % would give a 2px hairline in a leaderboard row and a 10px
    // slab in a full card. Every other effect is a fixed thin line (meteor 2px, rain 1.5px) — that
    // constancy is what reads as density. The far channel is thinner, but only mildly: below ~1.2px
    // a hairline stops being drawn and starts being dithered.
    const w0 = far ? rnd(1.2, 1.7) : rnd(1.8, 2.6);

    // Run lengths are deliberately UNEVEN (one segment 5% of the height, the next 30%). Evenly
    // spaced nodes + strictly alternating sides + a constant swing is a sawtooth, and the eye reads
    // a regular sawtooth as a tilted ribbon no matter how many bends it has — that was the "too
    // wide and slanted" of the first version. A real bolt is long near-vertical runs broken by the
    // occasional sharp kink: the IRREGULARITY is the lightning, not the bend count.
    const weights = Array.from({ length: segments }, () => rnd(0.35, 2.2));
    const total = weights.reduce((a, b) => a + b, 0);
    const ys: number[] = [0];
    let acc = 0;
    for (let i = 0; i < segments; i++) {
      acc += (weights[i]! / total) * 100;
      ys.push(i === segments - 1 ? 100 : acc);
    }

    const xs: number[] = [];
    const ws: number[] = [];
    let side = rnd(0, 1) < 0.5 ? -1 : 1;
    for (let i = 0; i <= segments; i++) {
      const t = ys[i]! / 100;
      // The channel funnels into the strike: wide wander up top, tight near the ground. Physically
      // right, and it walks the eye down to the flare.
      const converge = 0.35 + 0.65 * (1 - t);
      // The tip is pinned to the centre so the ground flare needs no maths of its own.
      xs.push(i === segments ? 50 : 50 + side * swing() * converge);
      ws.push(w0 * Math.pow(1 - t, 0.9));
      // Only USUALLY flip. Two jogs the same way read as drift; always flipping draws a sine.
      if (rnd(0, 1) > 0.25) side = -side;
    }

    // Spurs that die in the air. A fork is THE lightning silhouette — every lightning icon ever
    // drawn has one — so every bolt gets TWO: one reads as an accident of the trunk, two read as a
    // channel branching, and they land at different heights. Never the top node and never the tip
    // (a spur off the strike point would read as a second bolt). Sizes are all relative, so a pill
    // gets the same fork proportionally as a card does.
    const branches: { at: number; dir: number; bx: number; by: number }[] = [];
    const cand: number[] = [];
    for (let i = 1; i <= segments - 2; i++) cand.push(i);
    // Enumerate the valid PAIRS and pick one, rather than picking a node and hunting for a partner:
    // the latter dead-ends whenever the first pick is the middle node of a short trunk, and that
    // bolt silently ends up with a single spur. Non-adjacent, or two spurs leaving the same side
    // would grow into each other. A trunk too short for any pair (4 segments) takes a lone spur —
    // better one fork than a bare line.
    const pairs: [number, number][] = [];
    for (let a = 1; a <= segments - 2; a++)
      for (let b = a + 2; b <= segments - 2; b++) pairs.push([a, b]);
    const picks: number[] = pairs.length
      ? pairs[Math.floor(rnd(0, pairs.length))]!
      : cand.length
        ? [cand[Math.floor(rnd(0, cand.length))]!]
        : [];
    for (const at of picks) {
      // Outward, i.e. the way the bolt already leans — inward would cross its own body.
      const dir = xs[at]! > 50 ? 1 : -1;
      // Reach generously sideways: the element is ~5x taller than wide and the trunk uses only a
      // third of that width, so a modest % barely moves the tip — the first version read as a kink
      // in the trunk. Clamped inside the box: the element paints nothing outside it, so an
      // over-long spur would just get its tip lopped off.
      //
      // A pill needs a shorter, stubbier spur. Its trunk swings wide (the swing is uncompensated
      // there, ~20-36%) so "outward" is not empty space, and with only 4-6 segments a card's drop
      // of 14-28% spans a whole segment — the spur runs straight into the trunk's next swing and
      // the outline crosses itself. Keeping the drop inside one segment keeps the contour simple.
      branches.push({
        at,
        dir,
        bx: Math.min(97, Math.max(3, xs[at]! + dir * (compact ? rnd(16, 26) : rnd(24, 44)))),
        by: Math.min(96, ys[at]! + (compact ? rnd(5, 10) : rnd(14, 28))),
      });
    }
    // Root thickness in px. A spur tapers root -> point, so its AVERAGE width is only half this:
    // at w0*0.7 that was ~0.65px — subpixel, i.e. invisible however far it reached.
    const bRoot = w0 * 0.9;

    // clip-path takes any <length-percentage>, so a point is a % plus an optional px offset — that
    // is what keeps the bolt a constant-width hairline on a size-relative zigzag.
    const co = (v: number, px = 0) =>
      px ? `calc(${v.toFixed(1)}% + ${px.toFixed(2)}px)` : `${v.toFixed(1)}%`;
    const P = (x: number, y: number, dxPx = 0, dyPx = 0) => `${co(x, dxPx)} ${co(y, dyPx)}`;

    const points: string[] = [];
    // Left edge, down to the tip. A left-going spur detours here: out to its tip, then back to a
    // hair below the root, then on down the trunk.
    for (let i = 0; i <= segments; i++) {
      points.push(P(xs[i]!, ys[i]!));
      const b = branches.find((x) => x.at === i && x.dir < 0);
      if (b) {
        points.push(P(b.bx, b.by));
        points.push(P(xs[i]!, ys[i]!, 0, bRoot));
      }
    }
    // Right edge, back up. A right-going spur detours here — same shape, walked in reverse.
    for (let i = segments - 1; i >= 0; i--) {
      const b = branches.find((x) => x.at === i && x.dir > 0);
      if (b) {
        points.push(P(xs[i]!, ys[i]!, ws[i]!, bRoot));
        points.push(P(b.bx, b.by));
      }
      points.push(P(xs[i]!, ys[i]!, ws[i]!));
    }

    return {
      left: `${rnd(12, 88).toFixed(1)}%`,
      // A pill is ~33px tall, so a card's ratio would leave the bolt ~8px wide — no room for a
      // zigzag to exist at all. Wider here buys the swing somewhere to go.
      '--ar': (compact ? rnd(0.34, 0.48) : rnd(0.2, 0.32)).toFixed(3),
      // Handed to ::before as a custom property (those inherit; clip-path does not) — see the css
      // for why the shape and the glow must not share an element.
      '--bolt': `polygon(${points.join(', ')})`,
      // Only a full-height bolt reaches this card's ground, so only it lights a flare.
      '--flare': far ? '0' : '1',
      ...(far
        ? {
            // Short: it hangs from the top edge (the cloud is above the frame either way) and its
            // taper — the tip is already a point — lets the channel simply dissolve mid-air, which
            // is what distance and haze do to one. aspect-ratio keeps the zigzag's angles, so a
            // shorter bolt is a proportionally narrower one for free.
            '--ph': `${rnd(36, 50).toFixed(0)}%`,
            '--op': rnd(0.45, 0.6).toFixed(2),
            // One wide layer ON TOP of the normal stack, never instead of it: the stack is what
            // keeps the core a dense hairline, and the wide one is the air scattering its light.
            // Opaque, like every other layer — a translucent wide blur is the smudge this effect's
            // css warns about.
            '--fx': `${BOLT_GLOW} drop-shadow(0 0 12px #7c3aed)`,
            animationName: 'cardfx-lightning-distant',
          }
        : {}),
      ...timing(dur),
    };
  },
  // The tip always lands on the spawn column (see above), so the flare needs no offset of its own.
  // Near bolts only: the far one's channel dissolves in mid-air a mile away and lands nothing here,
  // and the flood IS the landing — a hairline under a card-wide blaze would be invisible anyway.
  groundGlow: (p) => ({
    ...(p['--flare'] === '1' ? {} : { display: 'none' }),
    left: p.left ?? '50%',
    '--dur': p['--dur'] ?? '6s',
    '--delay': p['--delay'] ?? '0s',
  }),
  css: `
/*
 * The glow lives on this wrapper and the SHAPE lives on ::before — they must not share an element.
 * clip-path is applied AFTER filter, so on one element the clip cuts away the very halo the filter
 * just drew around the bolt, leaving a flat white line. That is why no amount of tuning the radius
 * did anything: the glow was never missing, it was being cropped off. Split in two, the filter sees
 * an already-clipped child and its halo has nowhere to be cut.
 *
 * STACKED, not widened: a shadow is a blurred copy of the shape, so one wide blur spreads a 1.9px
 * hairline's light over a huge area and its peak alpha collapses to nothing. Chained drop-shadows
 * each take the PREVIOUS result (shape plus the halo already drawn) as input, so tight ones compound
 * into a dense glow — the same reason the meteor's only halo is 3px. Keep every layer opaque; the
 * failure mode is one wide BRIGHT blur, which just smudges the line.
 */
/* One element, three phenomena (see the header). Everything a bolt needs is the DEFAULT, so the
   in-focus strike reads exactly as it always did; the far bolt and the flood are the same box told
   to be a different size, fill and glow. A flood sets --pw/--ph to 100% and --tx to 0, at which
   point width and height are both given and aspect-ratio simply stops applying — no unsetting
   needed. The far bolt sets only --ph, so aspect-ratio still derives its width and its zigzag keeps
   the same angles as every other bolt. */
.card-fx-lightning .p {
  top: 0;
  width: var(--pw, auto);
  height: var(--ph, 100%);
  /* Width follows the card's height, so the zigzag keeps its angles at any size. */
  aspect-ratio: var(--ar, 0.26);
  /* Centre the element on its spawn column: the tip is at the element's 50%. */
  translate: var(--tx, -50%) 0;
  /* The stacked halo belongs to a hairline, so the flood — which is nothing but diffuse light —
     passes --fx: none; drop-shadows on a soft gradient just smear a muddier copy of it around the
     edges. The far bolt keeps the whole stack and adds one wide layer for the haze. */
  filter: var(--fx, ${BOLT_GLOW});
  animation: cardfx-lightning-strike var(--dur, 6s) linear var(--delay, 0s) infinite;
}
.card-fx-lightning .p::before {
  content: '';
  position: absolute;
  inset: 0;
  background: var(--fill, #ffffff);
  clip-path: var(--bolt, none);
}
/* Dead for most of the cycle, then a double flicker — a single clean fade reads as a lamp, not a
   strike. Paused (reduced-motion) it rests on the 0% frame: invisible, card simply clean.
   The window is a % of --dur, so it widened when the cycle shortened — otherwise raising the strike
   rate would have quietly clipped each strike shorter. 10% of 3.5-5.5s ≈ 0.35-0.55s. */
@keyframes cardfx-lightning-strike {
  0%,
  86% {
    opacity: 0;
  }
  87% {
    opacity: var(--op, 1);
  }
  89% {
    opacity: calc(var(--op, 1) * 0.3);
  }
  91% {
    opacity: var(--op, 1);
  }
  96%,
  100% {
    opacity: 0;
  }
}
/* FAR — the same double-beat as the near bolt, because it IS the same event; only the tail differs.
   It lingers instead of snapping off (96% -> 99%): the bolt's own light stops instantly, but the air
   between here and there keeps handing it back for a moment. That lag is most of what says "far". */
@keyframes cardfx-lightning-distant {
  0%,
  84% {
    opacity: 0;
  }
  87% {
    opacity: var(--op, 0.5);
  }
  89% {
    opacity: calc(var(--op, 0.5) * 0.3);
  }
  91% {
    opacity: var(--op, 0.5);
  }
  99%,
  100% {
    opacity: 0;
  }
}
/* NEAR — the strike lands ON the card and the light swallows the frame. No bolt: at this distance
   the channel is wider than the shot, so there is nothing left to see a silhouette of.
   The window is deliberately a sliver of a long cycle (~0.3s of 9.5-15s). Two reasons, and the
   second is not negotiable: a close strike is a rare event, and a full-field flash is not a hairline
   — flashing the whole card on the bolt's ~1.5s rhythm would be a strobe. Two flashes every ~12s
   sits far inside the 3-per-second flash guidance; keep it that way if you retune this.
   These stops are a % of --dur, so they are the flash's LENGTH as well as its place: shortening the
   cycle without widening them here makes the flash briefer, not just more frequent. */
@keyframes cardfx-lightning-flood {
  0%,
  97.6% {
    opacity: 0;
  }
  98.05% {
    opacity: var(--op, 0.55);
  }
  98.5% {
    opacity: calc(var(--op, 0.55) * 0.3);
  }
  98.95% {
    opacity: var(--op, 0.55);
  }
  99.9%,
  100% {
    opacity: 0;
  }
}
/* The flare speaks the same language as every other ground glow — a dense 2px line with a gradient
   falloff — just brighter and wider, because this one is a strike and not a landing. A radial oval
   was the first attempt and read as cheap: the density lives in the hairline, not in a soft blob. */
.card-fx-lightning .g {
  width: 44px;
  height: 2px;
  margin-left: -22px;
  border-radius: 2px;
  background: linear-gradient(to right, transparent, #ffffff 42%, #ffffff 58%, transparent);
  box-shadow:
    0 0 9px #a78bfa,
    0 0 20px #7c3aed;
  animation: cardfx-lightning-flare var(--dur, 6s) linear var(--delay, 0s) infinite;
}
/* A low bloom licking up off the impact — kept faint and small so the line above stays the subject. */
.card-fx-lightning .g::before {
  content: '';
  position: absolute;
  left: 50%;
  bottom: 0;
  width: 30px;
  height: 13px;
  translate: -50% 0;
  background: radial-gradient(closest-side at 50% 100%, rgba(196, 181, 253, 0.5), transparent 72%);
}
/* Phased to the bolt above, keyframe for keyframe — the flare IS the strike landing. */
@keyframes cardfx-lightning-flare {
  0%,
  86% {
    opacity: 0;
    transform: scaleX(0.2);
  }
  87% {
    opacity: var(--op, 1);
    transform: scaleX(1);
  }
  89% {
    opacity: calc(var(--op, 1) * 0.35);
  }
  91% {
    opacity: calc(var(--op, 1) * 0.9);
    transform: scaleX(1.12);
  }
  96%,
  100% {
    opacity: 0;
    transform: scaleX(1.45);
  }
}
`,
};
